{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/consolekit\/activityindicator\/fail()"]}],"identifier":{"url":"doc:\/\/co.pointfree.VaporRouting\/documentation\/ConsoleKit\/ActivityIndicator\/fail()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fail","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["Linux"]}]},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Passes ","type":"text"},{"code":"ActivityIndicatorState.failure","type":"codeVoice"},{"text":" to the ","type":"text"},{"code":"ActivityIndicatorType","type":"codeVoice"},{"text":".","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Must be called after ","type":"text"},{"type":"codeVoice","code":"start(on:)"},{"text":" and completes the future returned by that method.","type":"text"}]}],"kind":"content"}],"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fail","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"s:10ConsoleKit17ActivityIndicatorC4failyyF","role":"symbol","modules":[{"name":"ConsoleKit"}],"roleHeading":"Instance Method","title":"fail()","symbolKind":"method"},"abstract":[{"text":"Stops the ","type":"text"},{"code":"ActivityIndicator","type":"codeVoice"},{"text":", yielding a failed \/ error appearance.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/co.pointfree.VaporRouting\/documentation\/ConsoleKit","doc:\/\/co.pointfree.VaporRouting\/documentation\/ConsoleKit\/ActivityIndicator"]]},"references":{"doc://co.pointfree.VaporRouting/documentation/ConsoleKit/ActivityIndicator":{"abstract":[{"text":"An instance of a ","type":"text"},{"code":"ActivityIndicatorType","type":"codeVoice"},{"text":" that can be started, failed, and succeeded.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActivityIndicator","kind":"identifier"}],"navigatorTitle":[{"text":"ActivityIndicator","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/ConsoleKit\/ActivityIndicator","url":"\/documentation\/consolekit\/activityindicator","title":"ActivityIndicator"},"doc://co.pointfree.VaporRouting/documentation/ConsoleKit":{"abstract":[],"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/ConsoleKit","url":"\/documentation\/consolekit","title":"ConsoleKit"},"doc://co.pointfree.VaporRouting/documentation/ConsoleKit/ActivityIndicator/fail()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fail","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","title":"fail()","role":"symbol","type":"topic","url":"\/documentation\/consolekit\/activityindicator\/fail()","abstract":[{"type":"text","text":"Stops the "},{"type":"codeVoice","code":"ActivityIndicator"},{"type":"text","text":", yielding a failed \/ error appearance."}],"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/ConsoleKit\/ActivityIndicator\/fail()"}}}