{"variants":[{"paths":["\/documentation\/niohttp2\/niohttp2errors\/ioonclosedconnection\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"NIOHTTP2"}],"role":"collectionGroup","title":"Equatable Implementations"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/IOOnClosedConnection\/Equatable-Implementations","interfaceLanguage":"swift"},"sections":[],"kind":"article","topicSections":[{"identifiers":["doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/IOOnClosedConnection\/!=(_:_:)"],"generated":true,"title":"Operators"}],"hierarchy":{"paths":[["doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/IOOnClosedConnection"]]},"references":{"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/NIOHTTP2Errors":{"abstract":[{"type":"text","text":"Errors that NIO raises when handling HTTP\/2 connections."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NIOHTTP2Errors"}],"role":"symbol","type":"topic","url":"\/documentation\/niohttp2\/niohttp2errors","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NIOHTTP2Errors"}],"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors","title":"NIOHTTP2Errors"},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2":{"type":"topic","url":"\/documentation\/niohttp2","kind":"symbol","title":"NIOHTTP2","abstract":[],"role":"collection","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2"},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/NIOHTTP2Errors/IOOnClosedConnection":{"type":"topic","url":"\/documentation\/niohttp2\/niohttp2errors\/ioonclosedconnection","abstract":[{"text":"An attempt to perform I\/O was made on a connection that is already closed.","type":"text"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IOOnClosedConnection","kind":"identifier"}],"navigatorTitle":[{"text":"IOOnClosedConnection","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/IOOnClosedConnection","kind":"symbol","title":"NIOHTTP2Errors.IOOnClosedConnection"},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/NIOHTTP2Errors/IOOnClosedConnection/!=(_:_:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"!=(_:_:)","url":"\/documentation\/niohttp2\/niohttp2errors\/ioonclosedconnection\/!=(_:_:)","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/IOOnClosedConnection\/!=(_:_:)","abstract":[],"type":"topic","kind":"symbol","role":"symbol"}}}