{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/ExcessiveEmptyDataFrames\/Equatable-Implementations","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"title":"Operators","identifiers":["doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/ExcessiveEmptyDataFrames\/!=(_:_:)"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors","doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/ExcessiveEmptyDataFrames"]]},"kind":"article","metadata":{"role":"collectionGroup","modules":[{"name":"NIOHTTP2"}],"title":"Equatable Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/niohttp2\/niohttp2errors\/excessiveemptydataframes\/equatable-implementations"]}],"references":{"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/NIOHTTP2Errors":{"abstract":[{"type":"text","text":"Errors that NIO raises when handling HTTP\/2 connections."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NIOHTTP2Errors"}],"role":"symbol","type":"topic","url":"\/documentation\/niohttp2\/niohttp2errors","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NIOHTTP2Errors"}],"identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors","title":"NIOHTTP2Errors"},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/NIOHTTP2Errors/ExcessiveEmptyDataFrames":{"url":"\/documentation\/niohttp2\/niohttp2errors\/excessiveemptydataframes","kind":"symbol","navigatorTitle":[{"text":"ExcessiveEmptyDataFrames","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/ExcessiveEmptyDataFrames","abstract":[{"text":"The remote peer has sent an excessive number of empty DATA frames, which looks like a denial of service","type":"text"},{"text":" ","type":"text"},{"text":"attempt, so the connection has been closed.","type":"text"}],"type":"topic","title":"NIOHTTP2Errors.ExcessiveEmptyDataFrames","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ExcessiveEmptyDataFrames","kind":"identifier"}]},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2":{"type":"topic","url":"\/documentation\/niohttp2","kind":"symbol","title":"NIOHTTP2","abstract":[],"role":"collection","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2"},"doc://co.pointfree.VaporRouting/documentation/NIOHTTP2/NIOHTTP2Errors/ExcessiveEmptyDataFrames/!=(_:_:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/niohttp2\/niohttp2errors\/excessiveemptydataframes\/!=(_:_:)","role":"symbol","title":"!=(_:_:)","identifier":"doc:\/\/co.pointfree.VaporRouting\/documentation\/NIOHTTP2\/NIOHTTP2Errors\/ExcessiveEmptyDataFrames\/!=(_:_:)","abstract":[],"type":"topic","kind":"symbol"}}}